### ISSUE TITLE
kitchensink shows empty page

### ISSUE THREAD

**Issue by oneneno** [mway-io/The-M-Project-Sample-Apps#8]
i have installed all things i needed on windows and osx and run:

C:\The-M-Project-Sample-Apps\kitchensink>grunt server
Running "server" task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "createDefaultTemplate" task

Running "tmpl:compile" (tmpl) task

> > Destination not written because compiled files were empty.

Running "configureProxies" task
Proxy created for: /myServer to your.server.com:80

Running "connect:livereload" (connect) task
Started connect web server on localhost:9000.

Running "open:server" (open) task

Running "watch:livereload" (watch) task
Waiting...

But i still have an empty web page on localhost:9000 ! What have i doing wrong ?

**Comment by stefanbuck** [comment]
Hi @oneneno,

sorry for that late reply. There was some trouble with Hammer.js v1.0.6 and The-M-Project v2.0.0-beta. We fix that with v2.0.0-beta2. Please try it again.

Regards
Stefan
